title: 湛泸兔子
email: yuchenglong01@foxmail.com
description: >-
  Stand on the shoulder of giants
lang: zh-CN
timezone: Asia/Shanghai
baseurl: ""
url: "https://zhanlutuzi.github.io"
domain: zhanlutuzi.github.io
github_username: zhanlutuzi
theme: minima
header_pages:
  - about.markdown
  - archives.md
  - categories.md
  - tags.md
  - friends.md
  - contact.md

author: zhanlutuzi

profile:
  name: zhanlutuzi
  career: GISer
  intro: 一名在前端与 GIS 领域努力奔跑的程序猿。

social:
  github: https://github.com/zhanlutuzi
  email: mailto:yuchenglong01@foxmail.com
  shortname: zhanlutuzi

markdown: kramdown
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - scripts
